---
name: Run unit tests
on:  # yamllint disable-line rule:truthy
  push:
    paths-ignore:
      - '*.md'
      - 'Changelog'
      - dist.ini
  pull_request:
    branches:
      # ignores new tags pushed
      - '**'

jobs:
  prove:
    runs-on: ubuntu-latest
    name: prove CLI execution
    strategy:
      matrix:
        platform:
          - alpine
          - debian
          - rockylinux
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        # not using Dist::Zilla here because Ebirah does not supports authordeps
      - name: install-and-cache perl tools
        uses: tecolicom/actions-use-perl-tools@v1.1
        with:
          key: default
          sudo: true
          verbose: false
          tools: >-
            Class::Accessor
            DateTime
            DBD::SQLite
            Devel::CheckOS
            HTTP::Cookies
            HTTP::CookieJar::LWP
            HTML::Form
            HTTP::Request
            HTML::TreeBuilder::XPath
            Log::Log4perl
            LWP::Protocol::https
            Mozilla::PublicSuffix
            Perl::Tidy::Sweetened
            Pod::Tidy
            Set::Tiny
            Test::Exception
            Test::Pod
            Test::Pod::Coverage
            Test::TempDir::Tiny
            YAML::XS
      - name: unit tests
        run: prove -l
      - name: extended unit tests
        run: prove -l xt
