---
name: Run unit tests
on:  # yamllint disable-line rule:truthy
  push:
    paths-ignore:
      - '*.md'
      - 'Changelog'
      - dist.ini
  pull_request:
    branches:
      # ignores new tags pushed
      - '**'

jobs:
  prove:
    runs-on: ubuntu-latest
    name: prove CLI execution
    strategy:
      matrix:
        platform:
          - alpine
          - debian
          - rockylinux
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        # not using Dist::Zilla here because Ebirah does not supports authordeps
      - name: install-and-cache perl tools
        uses: tecolicom/actions-use-perl-tools@v1.1
        with:
          key: default
          sudo: false
          verbose: false
          tools: >-
            Class::Accessor
            DBD::SQLite
            LWP::Protocol::https
            Pod::Tidy
            Perl::Tidy::Sweetened
            Test::Exception
      - name: unit tests
        run: prove -l
      - name: extended unit tests
        run: prove -l xt
