---
name: Dist::Zilla Action
on:
  push:
    paths-ignore:
      - README.md
      - Makefile
      - dist.ini
      - perlcriticrc
      - perltidyrc
      - tidyall.ini
      - TODO.txt
  pull_request:
    branches:
      - master

jobs:
  cpanm:
    runs-on: ubuntu-latest
    steps:
      - name: setup cpan CLI
        run: |
          mkdir -p "${HOME}/.cpan/build"
          mkdir -p "${HOME}/.cpan/prefs"
          mkdir -p "${HOME}/.cpan/sources"
          mkdir -p "${HOME}/.cpan/CPAN"
          cat << EOT
          $CPAN::Config = {
            'allow_installing_module_downgrades' => q[ask/no],
            'allow_installing_outdated_dists' => q[ask/no],
            'applypatch' => q[],
            'auto_commit' => q[0],
            'build_cache' => q[100],
            'build_dir' => q[${HOME}/.cpan/build],
            'build_dir_reuse' => q[0],
            'build_requires_install_policy' => q[yes],
            'bzip2' => q[/usr/bin/bzip2],
            'cache_metadata' => q[1],
            'check_sigs' => q[0],
            'cleanup_after_install' => q[0],
            'colorize_output' => q[0],
            'commandnumber_in_prompt' => q[1],
            'connect_to_internet_ok' => q[1],
            'cpan_home' => q[${HOME}/.cpan],
            'ftp_passive' => q[1],
            'ftp_proxy' => q[],
            'getcwd' => q[cwd],
            'gpg' => q[/usr/bin/gpg],
            'gzip' => q[/usr/bin/gzip],
            'halt_on_failure' => q[0],
            'histfile' => q[${HOME}/.cpan/histfile],
            'histsize' => q[100],
            'http_proxy' => q[],
            'inactivity_timeout' => q[0],
            'index_expire' => q[1],
            'inhibit_startup_message' => q[0],
            'keep_source_where' => q[${HOME}/.cpan/sources],
            'load_module_verbosity' => q[none],
            'make' => q[/usr/bin/make],
            'make_arg' => q[-j7],
            'make_install_arg' => q[-j7],
            'make_install_make_command' => q[/usr/bin/make],
            'makepl_arg' => q[],
            'mbuild_arg' => q[],
            'mbuild_install_arg' => q[],
            'mbuild_install_build_command' => q[./Build],
            'mbuildpl_arg' => q[],
            'no_proxy' => q[],
            'pager' => q[/usr/bin/less],
            'patch' => q[/usr/bin/patch],
            'perl5lib_verbosity' => q[none],
            'plugin_list' => [],
            'prefer_external_tar' => q[1],
            'prefer_installer' => q[MB],
            'prefs_dir' => q[${HOME}/.cpan/prefs],
            'prerequisites_policy' => q[follow],
            'pushy_https' => q[0],
            'recommends_policy' => q[1],
            'scan_cache' => q[atstart],
            'shell' => q[/bin/bash],
            'show_unparsable_versions' => q[0],
            'show_upload_date' => q[0],
            'show_zero_versions' => q[0],
            'suggests_policy' => q[0],
            'tar' => q[/usr/bin/tar],
            'tar_verbosity' => q[none],
            'term_is_latin' => q[1],
            'term_ornaments' => q[1],
            'test_report' => q[1],
            'trust_test_report_history' => q[0],
            'unzip' => q[/usr/bin/unzip],
            'urllist' => [q[https://www.cpan.org/]],
            'use_prompt_default' => q[0],
            'use_sqlite' => q[0],
            'version_timeout' => q[15],
            'wget' => q[/usr/bin/wget],
            'yaml_load_code' => q[0],
            'yaml_module' => q[YAML::XS],
          };
          1;
          __END__
          EOT > ${HOME}/.cpan/CPAN/MyConfig.pm
        echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> "${HOME}/.bashrc"
        echo 'CPAN_SQLITE_NO_LOG_FILES=1' >> "${HOME}/.bashrc"
        echo 'CPAN_SQLITE_LOG_FILES_CLEANUP=1' >> "${HOME}/.bashrc"
      - name: Dist::Zilla author dependencies
        run: cpan install Dist::Zilla::PluginBundle::Starter
  dzil:
    runs-on: ubuntu-latest
    name: "dzil run"
    needs: cpanm
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
      - name: Installing dependencies and testing all using dzil
        uses: jonasbn/github-action-perl-dist-zilla@0.10.0
        with:
          dzil-arguments: 'test --all'
