---
name: Dist::Zilla Action
on:
  pull_request:
    branches:
      - master

jobs:
  dzil:
    runs-on: ubuntu-latest
    name: "dzil run"
    steps:
      - name: install cpanm
        run: |
          apt-get update
          apt-get install -y cpanminus
      - name: Dist::Zilla author dependencies
        run: cpanm install Dist::Zilla::PluginBundle::Starter
      - name: Check out repository
        uses: actions/checkout@v4.1.7
      - name: Installing dependencies and testing all using dzil
        uses: jonasbn/github-action-perl-dist-zilla@0.4.0
        with:
          dzil-arguments: 'test --all'
