---
name: Dist::Zilla Action
on:
  pull_request:
    branches:
      - master

jobs:
  dzil:
    runs-on: ubuntu-latest
    name: "dzil run"
    steps:
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          cpanminus
      - name: Dist::Zilla author dependencies
        run: sudo cpanm install Dist::Zilla::PluginBundle::Starter
      - name: Check out repository
        uses: actions/checkout@v4.1.7
      - name: Installing dependencies and testing all using dzil
        uses: jonasbn/github-action-perl-dist-zilla@0.5.5
        with:
          dzil-arguments: 'test --all'
